# Generated by Django 2.2 on 2020-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='desc',
            field=models.TextField(max_length=50),
        ),
    ]
