# Generated by Django 2.2 on 2020-10-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200927_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='qty',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
