# Generated by Django 2.2 on 2020-10-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20201001_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='qty',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
