# Generated by Django 2.2 on 2020-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201011_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prod',
            name='stok',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
