# Generated by Django 2.2 on 2020-09-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='stok',
        ),
    ]
