# Generated by Django 2.2 on 2020-09-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_prod_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='stok',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
