# Generated by Django 2.2 on 2020-10-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201011_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='prod',
            name='stok',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
