# Generated by Django 2.2 on 2020-09-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200929_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stok',
        ),
    ]
