# Generated by Django 2.2 on 2020-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201001_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prod',
            name='stok',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
